### ISSUE TITLE
How to change "Add to Apple Wallet" font size

### ISSUE THREAD

**Issue by CherukuriSiva** [reeq-dev/react-native-passkit#1]
In iOS "Add to Apple Wallet" font size is big compared to my project's design system. So please guide us to change "Add to Apple Wallet" font size.

**Comment by reeq-dev** [comment]
@CherukuriSiva 
Font size of "Add to Apple Wallet" button is based on the dimensions of button itself. That means we cant change font size directly. So your problem can be solved by playing with a different button's height and width to match the perfect proportions e.g:
`style={Platform.OS === 'ios' ? { height: 60, width: 140 } : undefined }`
After that font size will be changed automatically (same for paddings).
Also known issue regarding the border radius for iOS 16.1 +
https://developer.apple.com/forums/thread/720929
